# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme
- jekyll-analytics

jekyll-analytics:
  GoogleAnalytics:
    id: UA-146577403-1
    anonymizeIp: false

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Ryan Ng'
# description: 'This is my new website'
permalink: pretty
logo: "/assets/logos/prof-pic.png"

# Pagination
# paginate: 5
# paginate_path: projects/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Projects
  url: /projects/
- title: GitHub
  url: https://github.com/nayrng
- title: Résumé
  url: /resume/
- title: Contact Me
  url: /contact/  

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
  
# Google Analytics
google_analytics: UA-146577403-1

# Collections
collections:
  posts:
    title: Projects
    output: true
    description: "My personal projects"
    feature_text: |
    feature_image: "/assets/headers/projects_header.png"
